development:
#  adapter: mysql2
#  reconnect: false
#  database: importrequire
#  pool: 5
#  username: importrequire
#  password: importrequ1re
#  host: localhost
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  reconnect: false
  database: importrequire
  pool: 5
  username: importrequire
  password: importrequ1re
  host: localhost
#  adapter: sqlite3
#  database: db/production.sqlite3
#  pool: 5
#  timeout: 5000
